name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  folders:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          dir_names: true
          matrix: true
          dir_names_exclude_current_dir: true

  build:
    runs-on: ubuntu-latest
    needs: folders
    strategy:
      matrix:
        image: ${{ fromJSON(needs.folders.outputs.images) }}
    steps:
      - name: Display current job
        run: echo ${{matrix.image}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{matrix.image}}
          file: ${{matrix.image}}/Dockerfile
          push: true
          tags: ghcr.io/camfu-co/${{matrix.image}}:latest